services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: frontend
    networks:
      - gateway
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - .env
    restart: unless-stopped

networks:
  gateway:
    name: back_gateway
    external: true