export const ebcTooltipContent = "Unité qui indique la couleur de la bière : plus le chiffre est élevé, plus la bière est foncée."
export const ibuTooltipContent = "Unité qui mesure l'amertume de la bière : plus le chiffre est élevé, plus la bière est amère."
export const boilingIngredientToolTipContent = "Il s'agit des ingrédients à ajouter lors de la phase d'ébullition. Notamment les houblons, sucres ou divers (fruits, épices…)"
export const postBoilingTooltipContent = "Ajout d'ingrédients après l'ébullition, hors du feu, pour préserver les arômes."
export const multiPalierTooltipContent = "Méthode où la température de brassage change par étapes, pour une meilleure extraction des sucres et contrôler le profil aromatique de la bière."
export const mashoutTooltipContent = "Dernière étape, facultative, de l'empâtage : on chauffe le mélange entre 75°C et 77°C pour stopper l’activité enzymatique et améliorer la « fermentabilité » du moût."
export const fermentationIngredientToolTipContent = "Levures* : Souche(s) utilisé(es) pour la fermentation de la bière\nSucre* : Ingrédient qui servira au resucrage\nHoublons : Les houblons ajoutés ici servent au dry-hoping. Il s’agit d’une méthode pour récupérer les arômes du houblon"
export const fermentationIngredientDiversTooltipContent = "Test Divers"